image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 3306 # MySQL
  onOpen: ignore
- port: 8080
  onOpen: open-preview
  # onOpen: ignore

# start up tasks
tasks:
  # init: Will be executed one time when creating a workspace, command: will be exected each time you open workspace
  - init: |
      composer update --no-interaction --prefer-dist
      mysql -e "CREATE DATABASE IF NOT EXISTS yalitresoredb_test;"
      mysql -e "CREATE DATABASE IF NOT EXISTS yalitresoredb;"
      chmod +x ./yii
      chmod +x ./tests/bin/yii
      ./yii migrate --migrationPath=@yii/rbac/migrations --interactive=0
      ./yii migrate --migrationNamespaces=Da\\User\\Migration --interactive=0
      ./yii migrate --interactive=0
      ./tests/bin/yii migrate --migrationPath=@yii/rbac/migrations --interactive=0
      ./tests/bin/yii migrate --migrationNamespaces=Da\\User\\Migration --interactive=0
      ./tests/bin/yii migrate --interactive=0
      chmod +x admin-create.bat
      ./admin-create.bat
    command: |
      ./yii serve 0.0.0.0
  # - command: gp await-port 8080 && ./vendor/bin/codecept run --coverage
  - command: gp await-port 8080 && gp preview $(gp url 8080)
